kind: trl_dpo
planned_tokens: null
peft: null
args:
  output_dir: ${experiment_dir}/ckpts
  beta: 0.1
  max_steps: -1
  num_train_epochs: 1
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  learning_rate: 5.0e-7
  logging_steps: 1
  eval_strategy: "no"
  save_steps: 200
  bf16: false
  seed: ${seed}
